config/routes.rb
Moaz::Application.routes.draw do
  
  match '/editor(/*requested_uri)' => 'mercury_auth#edit', :as => :mercury_editor

  Mercury::Engine.routes

  resources :posts do
    member { post :mercury_update }
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :users
  resources :testimonials, :except => [:show]

  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/signup', :to => 'users#new'

  match 'home' => "pages#home"  
  match '/about', :to => 'pages#about', :via => :get, :as => :about
  match '/profile', :to => 'pages#profile'
  match '/amir-bio', :to => 'pages#amir_bio'
  match '/contact', :to => 'pages#contact'

  resources :properties do
    resources :pictures do
      collection { post :sort }
    end
    resources :options
  end

  resources :galleries do
    resources :pictures do
      collection { post :sort }
    end
  end

  root :to => 'pages#home'

end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :address, :price, :beds, :baths, :sqft, :neighborhood, :description, :status

  has_many :pictures, :as => :imageable, :dependent => :destroy
  has_many :options, :dependent => :destroy

  validates :address, :price, :beds, :baths, :sqft, :neighborhood, :description, :presence => true 

  before_save :add_slug

  def to_param
    self.slug
  end

  private

  def add_slug
    self.slug = self.address.parameterize
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :authenticate_with_admin, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @properties = Property.order("status ASC")
  end

  def show
    @property = Property.find_by_slug(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(params[:property])
    if @property.save
      flash[:notice] = "Successfully created property."
      redirect_to @property
    else
      render :action => "new"
    end
  end

  def edit
    @property = Property.find_by_slug(params[:id])
  end

  def update
    @property = Property.find_by_slug(params[:id])
    if @property.update_attributes(params[:property])
      flash[:notice] = "Successfully updated property."
      redirect_to @property
    else
      render :action => "edit"
    end
  end

  def destroy
    @property = Property.find_by_slug(params[:id])
    @property.destroy
    flash[:notice] = "Successfully destroyed property."
    redirect_to properties_url
  end

end

app/helpers/properties_helper.rb
module PropertiesHelper
  def short_address(address)
    if !address.index(',').nil?
      address.slice(0, address.index(','))
    else
      address
    end
  end
end

app/views/properties/_admin_links.html.erb
<% if current_user && current_user.admin? %>
<div class="border-bot">
  <%= link_to "Add a Picture", new_property_picture_path(@property), :class => "button" %> 
  <%= link_to "Add an Option", new_property_option_path(@property), :class => "button" %> 
  <%= link_to "Edit Property", edit_property_path(@property), :class => "button"  %>
  <%= link_to "Remove Property", @property, :confirm => "Are you sure?", :method => :delete, :class => "button" %> 
</div>
<% end %>

app/views/properties/_form.html.erb
<%= form_for @property do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select(:status, [['Available', 'available'], ['Under Contract', 'under contract'],['In Construction', 'in construction'], ['Sold', 'sold']]) %>
  </div> 
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
  <div class="field">
    <%= f.label :neighborhood %><br />
    <%= f.text_field :neighborhood %>
  </div> 
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div> 
  <div class="field">
    <%= f.label :beds %><br />
    <%= f.text_field :beds %>
  </div> 
  <div class="field">
    <%= f.label :baths %><br />
    <%= f.text_field :baths %>
  </div> 
  <div class="field">
    <%= f.label :sqft %><br />
    <%= f.text_field :sqft %>
  </div> 
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div> 
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/properties/_pictures.html.erb
  <% if @property.pictures.count > 0 %>
    <% if current_user && current_user.admin? %>
      <ul id="pictures" data-update-url="<%= sort_property_pictures_path(@property) %>">
        <% @property.pictures.each do |picture| %>
          <%= content_tag_for :li, picture do %>
              <%= image_tag picture.image_url(:small_thumb) if picture.image? %>
              <div class="actions">
                <%= link_to "edit", edit_property_picture_path(@property, picture) %> |
                <%= link_to "remove", property_picture_path(@property, picture), :confirm => 'Are you sure?', :method => :delete %>
              </div>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <div id="slides">
        <% for picture in @property.pictures %>
          <a href="<%= picture.image_url %>">
          <%= image_tag picture.image_url(:large) if picture.image? %>
          </a>
        <% end %>
      </div>
      <% if @property.pictures.count > 1 %>
      <div class="slide-nav">
        <a id="prev" href="#">Prev</a> | 
        <a id="next" href="#">Next</a>
      </div>
      <% end %>
    <% end %>
  <% end %>

app/views/properties/create.html.erb
<h1>Properties#create</h1>
<p>Find me in app/views/properties/create.html.erb</p>

app/views/properties/destroy.html.erb
<h1>Properties#destroy</h1>
<p>Find me in app/views/properties/destroy.html.erb</p>

app/views/properties/edit.html.erb
<h2>Editing <%= @property.address %></h2>

<%= render 'form' %>

<p><%= link_to "Back to List", properties_path %></p>

app/views/properties/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "properties" %>
<% end %>

<h1>
  <strong>Our</strong> Properties 
  <% if current_user && current_user.admin? %>
  <span><%= link_to "Add Property", new_property_path, :class => "button" %></span>
  <% end %>
</h1>
<% if @properties.count > 0 %>
  <% for property in @properties %>
    <div class="border-bot">
    	<div class="wrapper">
        <% if property.pictures.count > 0 %>
        <%= link_to first_thumb_link(property.pictures), property %>
        <% end %>
    		<h3 class="text-1">
          <%= link_to short_address(property.address), property %><%= " - #{property.status.titleize}" unless property.status.nil? %>
        </h3>
    		<span class="text-2">
          <strong><%= property.neighborhood %></strong>
          <ul class="details">
            <li>Price: <%= number_to_currency property.price, :precision => 0 %> | </li>
            <li>Beds: <%= property.beds %> | </li>
            <li>Baths: <%= number_with_precision property.baths, :precision => 1 %> | </li>
            <li>Sqft: <%= number_with_delimiter property.sqft %></li>
          </ul>
        </span>
    		<div class="alignright">
          <%= link_to "View", property, :class => "button" %>
        </div>
    	</div>
    </div>
  <% end %>
<% else %>
<p class="reg color-1">Sorry, there are currently no properties.<p>
<% end %>

app/views/properties/new.html.erb
<h2>Create a new property</h2>
<%= render 'form' %>
<p><%= link_to "Back to List", properties_path %></p>

app/views/properties/show.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "properties" %>
<% end %>

<% content_for :before_jquery do %>
  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
<% end %>

<% content_for :after_jquery do %>
  <%= javascript_include_tag "http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js" %>
  <%= javascript_include_tag 'cycle' %>
  <%= javascript_include_tag 'gmap3.min' %>
  <%= javascript_include_tag 'properties' %>
  <%= javascript_include_tag "FancyZoomHTML" %>
  <%= javascript_include_tag "FancyZoom" %>
<% end %>

<p>
  <%= link_to "&laquo; Back to properties".html_safe, properties_path %> 
</p>
<h1 class="border-bot"><%= @property.address %> <span><strong><%= number_to_currency @property.price, :precision => 0 %></strong></span></h1>
<%= render :partial => "admin_links" %>
<div class="col-1 indent-bot">
<%= render :partial => "pictures" %>
</div>
<div class="col-2">
  <h3>Property <strong>Details</strong><%= " - #{@property.status.titleize}" unless @property.status.nil? %></h3>
  <ul class="list-1 indent-bot">
  	<li>Price: <%= number_to_currency @property.price, :precision => 0 %></li>
  	<li>Beds: <%= @property.beds %></li>
  	<li>Baths: <%= number_with_precision @property.baths, :precision => 1 %></li>
  	<li>Sqft: <%= number_with_delimiter @property.sqft %></li>
  	<li><%= @property.neighborhood %></li>
  </ul>
</div>
<div style="clear: both"></div>
<div class="col-X">
  <p><%= raw @property.description %></p>
  <% if @property.options %>
  <h3 class="border-bot">Listing Info for <strong><%= short_address(@property.address) %></strong></h3>
  <ul class="list-1 condensed indent-bot">
    <% @property.options.each do |option| %>
      <li>
        <%= option.content %>
        <% if current_user && current_user.admin? %>
          <%= link_to "remove", property_option_path(@property, option), :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <% end %>
  <h3 class="border-bot">Map to <strong><%= short_address(@property.address) %></strong></h3>
  <div id="map" style="width: 100%; height: 300px;"></div>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#map").gmap3({
        action: 'addMarker',
        address: "<%= @property.address %>",
        map:{center:true, zoom:15}
      });
    });
  </script>
  <p>
    <%= link_to "&laquo; Back to properties".html_safe, properties_path %> 
  </p>
</div>

app/views/properties/update.html.erb
<h1>Properties#update</h1>
<p>Find me in app/views/properties/update.html.erb</p>