config/routes.rb
Moaz::Application.routes.draw do
  
  match '/editor(/*requested_uri)' => 'mercury_auth#edit', :as => :mercury_editor

  Mercury::Engine.routes

  resources :posts do
    member { post :mercury_update }
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :users
  resources :testimonials, :except => [:show]

  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/signup', :to => 'users#new'

  match 'home' => "pages#home"  
  match '/about', :to => 'pages#about', :via => :get, :as => :about
  match '/profile', :to => 'pages#profile'
  match '/amir-bio', :to => 'pages#amir_bio'
  match '/contact', :to => 'pages#contact'

  resources :properties do
    resources :pictures do
      collection { post :sort }
    end
    resources :options
  end

  resources :galleries do
    resources :pictures do
      collection { post :sort }
    end
  end

  root :to => 'pages#home'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  acts_as_list
  attr_accessible :title

  has_many :pictures, :as => :imageable, :dependent => :destroy

  validates_presence_of :title
  
  default_scope :order => "galleries.position ASC"

  before_save :add_slug

  def to_param
    self.slug
  end

  private

  def add_slug
    self.slug = self.title.parameterize
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_filter :authenticate_with_admin, :except => [:index, :show]
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find_by_slug(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(params[:gallery])
    if @gallery.save
      flash[:notice] = "Successfully created gallery."
      redirect_to @gallery
    else
      render :action => "new"
    end
  end

  def edit
    @gallery = Gallery.find_by_slug(params[:id])
  end

  def update
    @gallery = Gallery.find_by_slug(params[:id])
    if @gallery.update_attributes(params[:gallery])
      flash[:notice] = "Successfully updated gallery."
      redirect_to galleries_path
    else
      render :action => "edit"
    end
  end

  def destroy
    @gallery = Gallery.find_by_slug(params[:id])
    @gallery.destroy
    flash[:notice] = "Successfully destroyed gallery."
    redirect_to galleries_path
  end

end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_admin_links.html.erb
<% if current_user && current_user.admin? %>
<div class="border-bot">
  <%= link_to "Add a Picture", new_gallery_picture_path(@gallery), :class => "button" %> 
  <%= link_to "Edit Portfolio", edit_gallery_path(@gallery), :class => "button"  %>
  <%= link_to "Remove Portfolio", @gallery, :confirm => "Are you sure?", :method => :delete, :class => "button" %> 
</div>
<% end %>

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div> 
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/galleries/_pictures.html.erb
  <% if @gallery.pictures.count > 0 %>
    <% if current_user && current_user.admin? %>
      <ul id="pictures" data-update-url="<%= sort_gallery_pictures_path(@gallery) %>">
        <% @gallery.pictures.each do |picture| %>
          <%= content_tag_for :li, picture do %>
              <%= image_tag picture.image_url(:small_thumb) if picture.image? %>
              <div class="actions">
                <%= link_to "edit", edit_gallery_picture_path(@gallery, picture) %> |
                <%= link_to "remove", gallery_picture_path(@gallery, picture), :confirm => 'Are you sure?', :method => :delete %>
              </div>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <div id="slides">
        <% for picture in @gallery.pictures %>
          <%= image_tag picture.image_url(:large) if picture.image? %>
        <% end %>
      </div>
      <% if @gallery.pictures.count > 1 %>
      <div class="slide-nav">
        <a id="prev" href="#">Prev</a> | 
        <a id="next" href="#">Next</a>
      </div>
      <% end %>
    <% end %>
  <% end %>

app/views/galleries/create.html.erb
<h1>Galleries#create</h1>
<p>Find me in app/views/galleries/create.html.erb</p>

app/views/galleries/destroy.html.erb
<h1>Galleries#destroy</h1>
<p>Find me in app/views/galleries/destroy.html.erb</p>

app/views/galleries/edit.html.erb
<h1>Edit portfolio</h1>
<%= render :partial => "form" %>

app/views/galleries/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "galleries" %>
<% end %>

	<h1>
		<strong>Our</strong> Work
    <% if current_user && current_user.admin? %>
    <span><%= link_to "New Portfolio", new_gallery_path, :class => "button" %></span>
    <% end %>
	</h1>
  <div class="wrapper">
  <% if @galleries.count > 0 %>
    <% @galleries.each do |gallery| %>
        <% if gallery.pictures.count > 0 %>
        <div id="gallery">
          <div class="image">
            <%= link_to first_thumb_link(gallery.pictures), gallery %>
          </div>
          <h3 class="text-1">
            <%= link_to gallery.title, gallery %>
          </h3>
        </div>
        <% end %>
    <% end %>
  <% end %>
  </div>

app/views/galleries/new.html.erb
<h1>New Portfolio</h1>
<%= render :partial => "form" %>

app/views/galleries/show.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "galleries" %>
<% end %>

<% content_for :after_jquery do %>
  <%= javascript_include_tag "http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js" %>
  <%= javascript_include_tag 'cycle' %>
  <%= javascript_include_tag 'galleries' %>
<% end %>

<p>
  <%= link_to "&laquo; Back to portfolio".html_safe, galleries_path %> 
</p>
<h1 class="border-bot"><%= @gallery.title %></h1>
<%= render :partial => "admin_links" %>
<div class="indent-bot">
  <div id="gallery-pics">
    <%= render :partial => "pictures" %>
  </div>
</div>

app/views/galleries/update.html.erb
<h1>Galleries#update</h1>
<p>Find me in app/views/galleries/update.html.erb</p>