config/routes.rb
Moaz::Application.routes.draw do
  
  match '/editor(/*requested_uri)' => 'mercury_auth#edit', :as => :mercury_editor

  Mercury::Engine.routes

  resources :posts do
    member { post :mercury_update }
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :users
  resources :testimonials, :except => [:show]

  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/signup', :to => 'users#new'

  match 'home' => "pages#home"  
  match '/about', :to => 'pages#about', :via => :get, :as => :about
  match '/profile', :to => 'pages#profile'
  match '/amir-bio', :to => 'pages#amir_bio'
  match '/contact', :to => 'pages#contact'

  resources :properties do
    resources :pictures do
      collection { post :sort }
    end
    resources :options
  end

  resources :galleries do
    resources :pictures do
      collection { post :sort }
    end
  end

  root :to => 'pages#home'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :person, :address, :content, :position

  validates_presence_of :person, :content
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_filter :authenticate_with_admin, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @testimonials = Testimonial.all
  end

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.new(params[:testimonial])
    if @testimonial.save
      flash[:notice] = "Successfully created testimonial."
      redirect_to testimonials_path
    else
      render :action => "new"
    end
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def update
    @testimonial = Testimonial.find(params[:id])
    if @testimonial.update_attributes(params[:testimonial])
      flash[:notice] = "Successfully updated testimonial."
      redirect_to testimonials_path
    else
      render :action => "edit"
    end
  end

  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy
    flash[:notice] = "Successfully destroyed testimonial."
    redirect_to testimonials_path
  end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for @testimonial do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :person %><br />
    <%= f.text_field :person %>
  </div> 
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div> 
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/testimonials/create.html.erb
<h1>Testimonials#create</h1>
<p>Find me in app/views/testimonials/create.html.erb</p>

app/views/testimonials/destroy.html.erb
<h1>Testimonials#destroy</h1>
<p>Find me in app/views/testimonials/destroy.html.erb</p>

app/views/testimonials/edit.html.erb
<h1>Edit Testimonial</h1>
<%= render 'form' %>

app/views/testimonials/index.html.erb
<h1>
  <strong>What</strong> People Say
  <% if current_user && current_user.admin? %>
  <span><%= link_to "Add Testimonial", new_testimonial_path, :class => "button" %></span>
  <% end %>
</h1>
<ul>
<% for testimonial in @testimonials %>
  <div class="border-bot">
    <p class="text-1">
      <%= testimonial.person %> <%= testimonial.person[/and|&/] ? "say" : "says" %> . . . 
    </p>
    <p> about <%= testimonial.address %><br /><%= testimonial.content %></p>
    <% if current_user && current_user.admin? %>
    <span><%= link_to "Edit", edit_testimonial_path(testimonial), :class => "button" %></span>
    <span><%= link_to "Remove", testimonial, :confirm => "Are you sure?", :method => :delete, :class => "button" %></span>
    <% end %>
  </div>
<% end %>
</ul>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>
<%= render 'form' %>

app/views/testimonials/update.html.erb
<h1>Testimonials#update</h1>
<p>Find me in app/views/testimonials/update.html.erb</p>