config/routes.rb
Moaz::Application.routes.draw do
  
  match '/editor(/*requested_uri)' => 'mercury_auth#edit', :as => :mercury_editor

  Mercury::Engine.routes

  resources :posts do
    member { post :mercury_update }
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :users
  resources :testimonials, :except => [:show]

  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/signup', :to => 'users#new'

  match 'home' => "pages#home"  
  match '/about', :to => 'pages#about', :via => :get, :as => :about
  match '/profile', :to => 'pages#profile'
  match '/amir-bio', :to => 'pages#amir_bio'
  match '/contact', :to => 'pages#contact'

  resources :properties do
    resources :pictures do
      collection { post :sort }
    end
    resources :options
  end

  resources :galleries do
    resources :pictures do
      collection { post :sort }
    end
  end

  root :to => 'pages#home'

end

app/views/layouts/_content.html.erb
<div class="content">
  <div class="box">
  	<div class="box-top">
  		<div class="corner-top-left">
  			<div class="corner-top-right">
  				<div class="tail-top"></div>
  			</div>
  		</div>
  	</div>
  	<div class="tail-left">
  		<div class="tail-right">
  			<div class="box-content">
  				<div class="padding">
  					<div class="wrapper content-wrapper">
              <% flash.each do |key, value| %>
                <%= content_tag(:div, value, :class => "flash #{key}") %>
              <% end %>

              <%= yield %>
            </div>
  				</div>
  			</div>
  		</div>
  	</div>
  	<div class="box-bot">
  		<div class="corner-bot-left">
  			<div class="corner-bot-right">
  				<div class="tail-bot"></div>
  			</div>
  		</div>
  	</div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="wrapper">
		<ul class="menu-bot">
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "Properties", properties_path %>
      </li>
      <li>
        <%= link_to "Portfolio", galleries_path %>
      </li>
      <li>
        <%= link_to "Before & After", properties_path %>
      </li>
      <li>
        <%= link_to "Testimonials", testimonials_path %>
      </li>
      <li>
        <%= link_to "Profile", "/profile" %>
      </li>
			<li>
				<a href="/blog">Blog</a>
			</li>
		</ul>
		<div class="text-bot">
			<span>Moazami Homes &copy; <%= Time.now.year %></span>
      <%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	<div class="row-1">
		<div class="wrapper">
			<div class="logo">
        <%= link_to logo, root_path %>
			</div>
      <ul class="sub-menu">
      	<li>
          <%= link_to "Blog", posts_path %>
      	</li>
      	<li>
      		<a href="#">FAQ's</a>
      	</li>
      	<li>
          <% if signed_in? %>
          <%= link_to "Sign Out", signout_path, :class => 'last-item' %>
          <% else %>
          <%= link_to "Sign In", signin_path, :class => 'last-item' %>
          <% end %>
      	</li>
      </ul>
		</div>
	</div>
  <div class="row-2">
  	<div class="wrapper">
  		<ul class="menu">
  			<li>
          <%= link_to "Home", root_path %>
  			</li>
  			<li>
          <%= link_to "Properties", properties_path %>
  			</li>
  			<li>
          <%= link_to "Portfolio", galleries_path %>
  			</li>
  			<li>
          <%= link_to "Testimonials", testimonials_path %>
  			</li>
  			<li>
          <%= link_to "Profile", "/profile" %>
  			</li>
  			<li>
          <%= link_to "Contact Us", "/contact" %>
  			</li>
  		</ul>
  	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= yield :stylesheets %>
  <%= yield :before_jquery %>
  <%= javascript_include_tag "application" %>
  <%= yield :after_jquery %>
  <%= csrf_meta_tags %>
</head>
<body id="page1">
<div class="bg">
	<div class="main">

    <%= render 'layouts/header' %>

    <%= render 'layouts/content' %>

    <%= render 'layouts/footer' %>

  </div>
</div>
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury' %>
  </head>
  <body>
    <% if Rails.application.config.respond_to?(:mercury_config) %>
      <%= javascript_tag("jQuery.extend(Mercury.config, #{Rails.application.config.mercury_config});") %>
    <% end -%>

    <script type="text/javascript">
      var saveUrl = null;
      var options = {
        saveStyle: 'form',  // 'form', or 'json' (default json)
        saveMethod: null, // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>